name: on-pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deps:install
      run: npm run bootstrap
    - name: check:lint
      run: npm run check:lint
    - name: check:types
      run: npm run check:types
    - name: test
      run: npm run test:ci
